# Generated by Django 5.1.6 on 2025-03-05 03:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255, verbose_name="소속")),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("content", models.TextField(verbose_name="문의내용")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="등록일"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="처리여부"),
                ),
            ],
            options={
                "verbose_name": "문의",
                "verbose_name_plural": "문의",
                "ordering": ["-created_at"],
            },
        ),
    ]
